add_executable(zrinput_dictionary_compiler dictionary_compiler.cpp)
target_link_libraries(zrinput_dictionary_compiler PRIVATE zrinput_core)
zrinput_set_warnings(zrinput_dictionary_compiler)

add_executable(zrinput_query query_cli.cpp)
target_link_libraries(zrinput_query PRIVATE zrinput_core)
zrinput_set_warnings(zrinput_query)

add_executable(zrinput_long_benchmark long_composition_benchmark.cpp)
target_link_libraries(zrinput_long_benchmark PRIVATE zrinput_core)
zrinput_set_warnings(zrinput_long_benchmark)
